[workspace]
resolver = "2"
members = [
    "01_hello",
    "02_echor",
    "03_catr",
    "04_headr",
    "05_wcr",
    "06_uniqr",
    "07_findr",
    "08_cutr",
    "09_grepr",
    "10_commr",
    "11_tailr",
    "12_fortuner",
]
