[package]
name = "catr"
version = "0.1.0"
description = "Rust version of cat command."
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bstr = "1.12.0"
clap = { version = "4.5.38", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
