[package]
name = "headr"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.12.0"
clap = { version = "4.5.39", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
